// This file is generated by ZCL Advanced Platform generator.
// Modified manually for minimal Zigbee Router with Basic cluster only.

// The following is brought in by the endianness component, which all
// applications must include
#include "sl_endianness.h"

#ifndef SILABS_AF_ENDPOINT_CONFIG
#define SILABS_AF_ENDPOINT_CONFIG 1

// Default values for the attributes longer than a pointer, in a form of a
// binary blob. All attribute values with size greater than 2 bytes. Excluding 0
// values and externally saved values. Separate block is generated for
// big-endian and little-endian cases.

// String defaults: "Silvercrest" (11 chars), "LidlRouter" (10 chars), "1.0.0" (5 chars)
// Format: length byte followed by string characters
#define GENERATED_DEFAULTS_COUNT (29)
#define GENERATED_DEFAULTS { \
  /* 0: Manufacturer Name "Silvercrest" */ \
  11, 'S', 'i', 'l', 'v', 'e', 'r', 'c', 'r', 'e', 's', 't', \
  /* 12: Model Identifier "LidlRouter" */ \
  10, 'L', 'i', 'd', 'l', 'R', 'o', 'u', 't', 'e', 'r', \
  /* 23: SW Build ID "1.0.0" */ \
  5, '1', '.', '0', '.', '0' \
}

// Macro to reference defaults by offset
#define ZAP_LONG_DEFAULTS_INDEX(index) ((uint8_t*)&generatedDefaults[index])

// This is an array of EmberAfAttributeMinMaxValue structures.

#define GENERATED_MIN_MAX_DEFAULT_COUNT (0)
#define GENERATED_MIN_MAX_DEFAULTS { }


// Attribute count: Basic cluster (6 attrs)
#define GENERATED_ATTRIBUTE_COUNT (6)

// This is an array of EmberAfAttributeMetadata structures.
#define GENERATED_ATTRIBUTES { \
  /* Basic Cluster - Server */ \
  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x08 } }, /* 0 Cluster: Basic, Attribute: ZCL version, Side: server*/ \
  { 0x0004, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 12, (ATTRIBUTE_MASK_SINGLETON), { ZAP_LONG_DEFAULTS_INDEX(0) } }, /* 1 Cluster: Basic, Attribute: manufacturer name, Side: server*/ \
  { 0x0005, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 11, (ATTRIBUTE_MASK_SINGLETON), { ZAP_LONG_DEFAULTS_INDEX(12) } }, /* 2 Cluster: Basic, Attribute: model identifier, Side: server*/ \
  { 0x0007, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x01 } }, /* 3 Cluster: Basic, Attribute: power source, Side: server*/ \
  { 0x4000, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 6, (ATTRIBUTE_MASK_SINGLETON), { ZAP_LONG_DEFAULTS_INDEX(23) } }, /* 4 Cluster: Basic, Attribute: sw build id, Side: server*/ \
  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)3 } } /* 5 Cluster: Basic, Attribute: cluster revision, Side: server*/ \
}


// Cluster count: Basic only = 1
#define GENERATED_CLUSTER_COUNT (1)

// This is an array of EmberAfCluster structures.
#define GENERATED_CLUSTERS { \
  { 0x0000, (EmberAfAttributeMetadata*)&(generatedAttributes[0]), 6, 33, CLUSTER_MASK_SERVER, NULL } /* 0, Endpoint Id: 1, Cluster: Basic, Side: server*/ \
}


#define GENERATED_ENDPOINT_TYPE_COUNT (1)

// This is an array of EmberAfEndpointType structures.
#define GENERATED_ENDPOINT_TYPES { \
  { ((EmberAfCluster*)&(generatedClusters[0])), 1, 33 }, \
}

// Largest attribute size is needed for various buffers
#define ATTRIBUTE_LARGEST (12)

// Total size of singleton attributes (1 + 12 + 11 + 1 + 6 + 2 = 33)
#define ATTRIBUTE_SINGLETONS_SIZE (33)

// Total size of attribute storage
#define ATTRIBUTE_MAX_SIZE (0)

// Number of fixed endpoints
#define FIXED_ENDPOINT_COUNT (1)

// Array of endpoints that are supported, the data inside the array is the
// endpoint number.
#define FIXED_ENDPOINT_ARRAY { \
  1 \
}

// Array of profile ids (Home Automation)
#define FIXED_PROFILE_IDS { \
  260 \
}

// Array of device ids
#define FIXED_DEVICE_IDS { \
  8 \
}

// Array of device versions
#define FIXED_DEVICE_VERSIONS { \
  1 \
}

// Array of endpoint types supported on each endpoint
#define FIXED_ENDPOINT_TYPES { \
  0 \
}

// Array of networks supported on each endpoint
#define FIXED_NETWORKS { \
  0 \
}

// Array of EmberAfCommandMetadata structs.
#define ZAP_COMMAND_MASK(mask) COMMAND_MASK_ ## mask
#define EMBER_AF_GENERATED_COMMAND_COUNT (0)
#define GENERATED_COMMANDS { }

// Array of EmberAfManufacturerCodeEntry structures for commands.
#define GENERATED_COMMAND_MANUFACTURER_CODE_COUNT (0)
#define GENERATED_COMMAND_MANUFACTURER_CODES { { 0x00, 0x00 } }

// This is an array of EmberAfManufacturerCodeEntry structures for clusters.
#define GENERATED_CLUSTER_MANUFACTURER_CODE_COUNT (0)
#define GENERATED_CLUSTER_MANUFACTURER_CODES { \
  { 0x00, 0x00 } \
}

// This is an array of EmberAfManufacturerCodeEntry structures for attributes.
#define GENERATED_ATTRIBUTE_MANUFACTURER_CODE_COUNT (0)
#define GENERATED_ATTRIBUTE_MANUFACTURER_CODES { \
  { 0x00, 0x00 } \
}

// Array of EmberAfPluginReportingEntry structures.
#define EMBER_AF_GENERATED_REPORTING_CONFIG_DEFAULTS_TABLE_SIZE (0)
#define EMBER_AF_GENERATED_REPORTING_CONFIG_DEFAULTS { }


#define EMBER_AF_MANUFACTURER_CODE 0x1049
#define EMBER_AF_DEFAULT_RESPONSE_POLICY_ALWAYS

// All Enabled Clusters
#define ZCL_USING_BASIC_CLUSTER_SERVER

// Cluster Counts
#define EMBER_AF_BASIC_CLUSTER_SERVER_ENDPOINT_COUNT (1)

// All Enabled Cluster Attributes
#define ZCL_USING_BASIC_CLUSTER_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MANUFACTURER_NAME_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MODEL_IDENTIFIER_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_POWER_SOURCE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_SW_BUILD_ID_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE

#define EMBER_AF_SUPPORT_COMMAND_DISCOVERY


#endif // SILABS_AF_ENDPOINT_CONFIG
